---
# tasks file for roles/f5_role_as3
- name: Wait for API to be up
  bigip_wait:
    timeout: 150
    provider: "{{ provider }}"
  delegate_to: localhost

- name: Push AS3 Declaration
  uri:
    url: "https://{{ provider.server }}:{{ provider.server_port }}/mgmt/shared/appsvcs/declare"
    method: POST
    user: "{{ provider.user }}"
    password: "{{ provider.password }}"
    body: "{{ lookup('template', 'as3.j2') }}"
    status_code: 200
    timeout: 30
    body_format: json
    validate_certs: no
  register: as3_task
  delegate_to: localhost

- debug: var=as3_task.json.results

